"""Add total column to Bill

Revision ID: bd2a0566d9aa
Revises: 
Create Date: 2025-04-20 22:50:36.610050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd2a0566d9aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill')
    op.drop_table('subscriber')
    op.drop_table('usage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscriber_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('month', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usage_pkey')
    )
    op.create_table('subscriber',
    sa.Column('subscriber_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('subscriber_no', name='subscriber_pkey')
    )
    op.create_table('bill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscriber_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('month', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('total_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bill_pkey')
    )
    # ### end Alembic commands ###
